// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protobuf/pb_message.proto

package com.ociweb.protocoltest;

public final class PBMessageProvider {
  private PBMessageProvider() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PBQueryOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 user = 1;
    /**
     * <code>optional int32 user = 1;</code>
     */
    boolean hasUser();
    /**
     * <code>optional int32 user = 1;</code>
     */
    int getUser();

    // optional int32 year = 2;
    /**
     * <code>optional int32 year = 2;</code>
     */
    boolean hasYear();
    /**
     * <code>optional int32 year = 2;</code>
     */
    int getYear();

    // optional int32 month = 3;
    /**
     * <code>optional int32 month = 3;</code>
     */
    boolean hasMonth();
    /**
     * <code>optional int32 month = 3;</code>
     */
    int getMonth();

    // optional int32 date = 4;
    /**
     * <code>optional int32 date = 4;</code>
     */
    boolean hasDate();
    /**
     * <code>optional int32 date = 4;</code>
     */
    int getDate();

    // optional int32 sampleCount = 5;
    /**
     * <code>optional int32 sampleCount = 5;</code>
     */
    boolean hasSampleCount();
    /**
     * <code>optional int32 sampleCount = 5;</code>
     */
    int getSampleCount();

    // repeated .pbexample.PBQuery.PBSample samples = 6;
    /**
     * <code>repeated .pbexample.PBQuery.PBSample samples = 6;</code>
     */
    java.util.List<com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample> 
        getSamplesList();
    /**
     * <code>repeated .pbexample.PBQuery.PBSample samples = 6;</code>
     */
    com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample getSamples(int index);
    /**
     * <code>repeated .pbexample.PBQuery.PBSample samples = 6;</code>
     */
    int getSamplesCount();
    /**
     * <code>repeated .pbexample.PBQuery.PBSample samples = 6;</code>
     */
    java.util.List<? extends com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSampleOrBuilder> 
        getSamplesOrBuilderList();
    /**
     * <code>repeated .pbexample.PBQuery.PBSample samples = 6;</code>
     */
    com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSampleOrBuilder getSamplesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code pbexample.PBQuery}
   */
  public static final class PBQuery extends
      com.google.protobuf.GeneratedMessage
      implements PBQueryOrBuilder {
    // Use PBQuery.newBuilder() to construct.
    private PBQuery(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PBQuery(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PBQuery defaultInstance;
    public static PBQuery getDefaultInstance() {
      return defaultInstance;
    }

    public PBQuery getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PBQuery(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              user_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              year_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              month_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              date_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              sampleCount_ = input.readInt32();
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                samples_ = new java.util.ArrayList<com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample>();
                mutable_bitField0_ |= 0x00000020;
              }
              samples_.add(input.readMessage(com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          samples_ = java.util.Collections.unmodifiableList(samples_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ociweb.protocoltest.PBMessageProvider.internal_static_pbexample_PBQuery_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ociweb.protocoltest.PBMessageProvider.internal_static_pbexample_PBQuery_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ociweb.protocoltest.PBMessageProvider.PBQuery.class, com.ociweb.protocoltest.PBMessageProvider.PBQuery.Builder.class);
    }

    public static com.google.protobuf.Parser<PBQuery> PARSER =
        new com.google.protobuf.AbstractParser<PBQuery>() {
      public PBQuery parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PBQuery(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PBQuery> getParserForType() {
      return PARSER;
    }

    public interface PBSampleOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // optional int32 id = 1;
      /**
       * <code>optional int32 id = 1;</code>
       */
      boolean hasId();
      /**
       * <code>optional int32 id = 1;</code>
       */
      int getId();

      // optional int64 time = 2;
      /**
       * <code>optional int64 time = 2;</code>
       */
      boolean hasTime();
      /**
       * <code>optional int64 time = 2;</code>
       */
      long getTime();

      // optional int32 measurement = 3;
      /**
       * <code>optional int32 measurement = 3;</code>
       */
      boolean hasMeasurement();
      /**
       * <code>optional int32 measurement = 3;</code>
       */
      int getMeasurement();

      // optional int32 action = 4;
      /**
       * <code>optional int32 action = 4;</code>
       */
      boolean hasAction();
      /**
       * <code>optional int32 action = 4;</code>
       */
      int getAction();
    }
    /**
     * Protobuf type {@code pbexample.PBQuery.PBSample}
     */
    public static final class PBSample extends
        com.google.protobuf.GeneratedMessage
        implements PBSampleOrBuilder {
      // Use PBSample.newBuilder() to construct.
      private PBSample(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private PBSample(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final PBSample defaultInstance;
      public static PBSample getDefaultInstance() {
        return defaultInstance;
      }

      public PBSample getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private PBSample(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                id_ = input.readInt32();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                time_ = input.readInt64();
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                measurement_ = input.readInt32();
                break;
              }
              case 32: {
                bitField0_ |= 0x00000008;
                action_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ociweb.protocoltest.PBMessageProvider.internal_static_pbexample_PBQuery_PBSample_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ociweb.protocoltest.PBMessageProvider.internal_static_pbexample_PBQuery_PBSample_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample.class, com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample.Builder.class);
      }

      public static com.google.protobuf.Parser<PBSample> PARSER =
          new com.google.protobuf.AbstractParser<PBSample>() {
        public PBSample parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new PBSample(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<PBSample> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // optional int32 id = 1;
      public static final int ID_FIELD_NUMBER = 1;
      private int id_;
      /**
       * <code>optional int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }

      // optional int64 time = 2;
      public static final int TIME_FIELD_NUMBER = 2;
      private long time_;
      /**
       * <code>optional int64 time = 2;</code>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 time = 2;</code>
       */
      public long getTime() {
        return time_;
      }

      // optional int32 measurement = 3;
      public static final int MEASUREMENT_FIELD_NUMBER = 3;
      private int measurement_;
      /**
       * <code>optional int32 measurement = 3;</code>
       */
      public boolean hasMeasurement() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 measurement = 3;</code>
       */
      public int getMeasurement() {
        return measurement_;
      }

      // optional int32 action = 4;
      public static final int ACTION_FIELD_NUMBER = 4;
      private int action_;
      /**
       * <code>optional int32 action = 4;</code>
       */
      public boolean hasAction() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 action = 4;</code>
       */
      public int getAction() {
        return action_;
      }

      private void initFields() {
        id_ = 0;
        time_ = 0L;
        measurement_ = 0;
        action_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, id_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt64(2, time_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeInt32(3, measurement_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeInt32(4, action_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, id_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(2, time_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, measurement_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(4, action_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code pbexample.PBQuery.PBSample}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSampleOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.ociweb.protocoltest.PBMessageProvider.internal_static_pbexample_PBQuery_PBSample_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.ociweb.protocoltest.PBMessageProvider.internal_static_pbexample_PBQuery_PBSample_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample.class, com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample.Builder.class);
        }

        // Construct using com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          id_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          time_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000002);
          measurement_ = 0;
          bitField0_ = (bitField0_ & ~0x00000004);
          action_ = 0;
          bitField0_ = (bitField0_ & ~0x00000008);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.ociweb.protocoltest.PBMessageProvider.internal_static_pbexample_PBQuery_PBSample_descriptor;
        }

        public com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample getDefaultInstanceForType() {
          return com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample.getDefaultInstance();
        }

        public com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample build() {
          com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample buildPartial() {
          com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample result = new com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.id_ = id_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.time_ = time_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.measurement_ = measurement_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.action_ = action_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample) {
            return mergeFrom((com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample other) {
          if (other == com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample.getDefaultInstance()) return this;
          if (other.hasId()) {
            setId(other.getId());
          }
          if (other.hasTime()) {
            setTime(other.getTime());
          }
          if (other.hasMeasurement()) {
            setMeasurement(other.getMeasurement());
          }
          if (other.hasAction()) {
            setAction(other.getAction());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // optional int32 id = 1;
        private int id_ ;
        /**
         * <code>optional int32 id = 1;</code>
         */
        public boolean hasId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional int32 id = 1;</code>
         */
        public int getId() {
          return id_;
        }
        /**
         * <code>optional int32 id = 1;</code>
         */
        public Builder setId(int value) {
          bitField0_ |= 0x00000001;
          id_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 id = 1;</code>
         */
        public Builder clearId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          id_ = 0;
          onChanged();
          return this;
        }

        // optional int64 time = 2;
        private long time_ ;
        /**
         * <code>optional int64 time = 2;</code>
         */
        public boolean hasTime() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional int64 time = 2;</code>
         */
        public long getTime() {
          return time_;
        }
        /**
         * <code>optional int64 time = 2;</code>
         */
        public Builder setTime(long value) {
          bitField0_ |= 0x00000002;
          time_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int64 time = 2;</code>
         */
        public Builder clearTime() {
          bitField0_ = (bitField0_ & ~0x00000002);
          time_ = 0L;
          onChanged();
          return this;
        }

        // optional int32 measurement = 3;
        private int measurement_ ;
        /**
         * <code>optional int32 measurement = 3;</code>
         */
        public boolean hasMeasurement() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional int32 measurement = 3;</code>
         */
        public int getMeasurement() {
          return measurement_;
        }
        /**
         * <code>optional int32 measurement = 3;</code>
         */
        public Builder setMeasurement(int value) {
          bitField0_ |= 0x00000004;
          measurement_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 measurement = 3;</code>
         */
        public Builder clearMeasurement() {
          bitField0_ = (bitField0_ & ~0x00000004);
          measurement_ = 0;
          onChanged();
          return this;
        }

        // optional int32 action = 4;
        private int action_ ;
        /**
         * <code>optional int32 action = 4;</code>
         */
        public boolean hasAction() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>optional int32 action = 4;</code>
         */
        public int getAction() {
          return action_;
        }
        /**
         * <code>optional int32 action = 4;</code>
         */
        public Builder setAction(int value) {
          bitField0_ |= 0x00000008;
          action_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 action = 4;</code>
         */
        public Builder clearAction() {
          bitField0_ = (bitField0_ & ~0x00000008);
          action_ = 0;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:pbexample.PBQuery.PBSample)
      }

      static {
        defaultInstance = new PBSample(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:pbexample.PBQuery.PBSample)
    }

    private int bitField0_;
    // optional int32 user = 1;
    public static final int USER_FIELD_NUMBER = 1;
    private int user_;
    /**
     * <code>optional int32 user = 1;</code>
     */
    public boolean hasUser() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 user = 1;</code>
     */
    public int getUser() {
      return user_;
    }

    // optional int32 year = 2;
    public static final int YEAR_FIELD_NUMBER = 2;
    private int year_;
    /**
     * <code>optional int32 year = 2;</code>
     */
    public boolean hasYear() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 year = 2;</code>
     */
    public int getYear() {
      return year_;
    }

    // optional int32 month = 3;
    public static final int MONTH_FIELD_NUMBER = 3;
    private int month_;
    /**
     * <code>optional int32 month = 3;</code>
     */
    public boolean hasMonth() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 month = 3;</code>
     */
    public int getMonth() {
      return month_;
    }

    // optional int32 date = 4;
    public static final int DATE_FIELD_NUMBER = 4;
    private int date_;
    /**
     * <code>optional int32 date = 4;</code>
     */
    public boolean hasDate() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 date = 4;</code>
     */
    public int getDate() {
      return date_;
    }

    // optional int32 sampleCount = 5;
    public static final int SAMPLECOUNT_FIELD_NUMBER = 5;
    private int sampleCount_;
    /**
     * <code>optional int32 sampleCount = 5;</code>
     */
    public boolean hasSampleCount() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 sampleCount = 5;</code>
     */
    public int getSampleCount() {
      return sampleCount_;
    }

    // repeated .pbexample.PBQuery.PBSample samples = 6;
    public static final int SAMPLES_FIELD_NUMBER = 6;
    private java.util.List<com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample> samples_;
    /**
     * <code>repeated .pbexample.PBQuery.PBSample samples = 6;</code>
     */
    public java.util.List<com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample> getSamplesList() {
      return samples_;
    }
    /**
     * <code>repeated .pbexample.PBQuery.PBSample samples = 6;</code>
     */
    public java.util.List<? extends com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSampleOrBuilder> 
        getSamplesOrBuilderList() {
      return samples_;
    }
    /**
     * <code>repeated .pbexample.PBQuery.PBSample samples = 6;</code>
     */
    public int getSamplesCount() {
      return samples_.size();
    }
    /**
     * <code>repeated .pbexample.PBQuery.PBSample samples = 6;</code>
     */
    public com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample getSamples(int index) {
      return samples_.get(index);
    }
    /**
     * <code>repeated .pbexample.PBQuery.PBSample samples = 6;</code>
     */
    public com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSampleOrBuilder getSamplesOrBuilder(
        int index) {
      return samples_.get(index);
    }

    private void initFields() {
      user_ = 0;
      year_ = 0;
      month_ = 0;
      date_ = 0;
      sampleCount_ = 0;
      samples_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, user_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, year_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, month_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, date_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, sampleCount_);
      }
      for (int i = 0; i < samples_.size(); i++) {
        output.writeMessage(6, samples_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, user_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, year_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, month_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, date_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, sampleCount_);
      }
      for (int i = 0; i < samples_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, samples_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.ociweb.protocoltest.PBMessageProvider.PBQuery parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ociweb.protocoltest.PBMessageProvider.PBQuery parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ociweb.protocoltest.PBMessageProvider.PBQuery parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ociweb.protocoltest.PBMessageProvider.PBQuery parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ociweb.protocoltest.PBMessageProvider.PBQuery parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ociweb.protocoltest.PBMessageProvider.PBQuery parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.ociweb.protocoltest.PBMessageProvider.PBQuery parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.ociweb.protocoltest.PBMessageProvider.PBQuery parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.ociweb.protocoltest.PBMessageProvider.PBQuery parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ociweb.protocoltest.PBMessageProvider.PBQuery parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ociweb.protocoltest.PBMessageProvider.PBQuery prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pbexample.PBQuery}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.ociweb.protocoltest.PBMessageProvider.PBQueryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ociweb.protocoltest.PBMessageProvider.internal_static_pbexample_PBQuery_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ociweb.protocoltest.PBMessageProvider.internal_static_pbexample_PBQuery_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ociweb.protocoltest.PBMessageProvider.PBQuery.class, com.ociweb.protocoltest.PBMessageProvider.PBQuery.Builder.class);
      }

      // Construct using com.ociweb.protocoltest.PBMessageProvider.PBQuery.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSamplesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        user_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        year_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        month_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        date_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        sampleCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        if (samplesBuilder_ == null) {
          samples_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          samplesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ociweb.protocoltest.PBMessageProvider.internal_static_pbexample_PBQuery_descriptor;
      }

      public com.ociweb.protocoltest.PBMessageProvider.PBQuery getDefaultInstanceForType() {
        return com.ociweb.protocoltest.PBMessageProvider.PBQuery.getDefaultInstance();
      }

      public com.ociweb.protocoltest.PBMessageProvider.PBQuery build() {
        com.ociweb.protocoltest.PBMessageProvider.PBQuery result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ociweb.protocoltest.PBMessageProvider.PBQuery buildPartial() {
        com.ociweb.protocoltest.PBMessageProvider.PBQuery result = new com.ociweb.protocoltest.PBMessageProvider.PBQuery(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.user_ = user_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.year_ = year_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.month_ = month_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.date_ = date_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.sampleCount_ = sampleCount_;
        if (samplesBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020)) {
            samples_ = java.util.Collections.unmodifiableList(samples_);
            bitField0_ = (bitField0_ & ~0x00000020);
          }
          result.samples_ = samples_;
        } else {
          result.samples_ = samplesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ociweb.protocoltest.PBMessageProvider.PBQuery) {
          return mergeFrom((com.ociweb.protocoltest.PBMessageProvider.PBQuery)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ociweb.protocoltest.PBMessageProvider.PBQuery other) {
        if (other == com.ociweb.protocoltest.PBMessageProvider.PBQuery.getDefaultInstance()) return this;
        if (other.hasUser()) {
          setUser(other.getUser());
        }
        if (other.hasYear()) {
          setYear(other.getYear());
        }
        if (other.hasMonth()) {
          setMonth(other.getMonth());
        }
        if (other.hasDate()) {
          setDate(other.getDate());
        }
        if (other.hasSampleCount()) {
          setSampleCount(other.getSampleCount());
        }
        if (samplesBuilder_ == null) {
          if (!other.samples_.isEmpty()) {
            if (samples_.isEmpty()) {
              samples_ = other.samples_;
              bitField0_ = (bitField0_ & ~0x00000020);
            } else {
              ensureSamplesIsMutable();
              samples_.addAll(other.samples_);
            }
            onChanged();
          }
        } else {
          if (!other.samples_.isEmpty()) {
            if (samplesBuilder_.isEmpty()) {
              samplesBuilder_.dispose();
              samplesBuilder_ = null;
              samples_ = other.samples_;
              bitField0_ = (bitField0_ & ~0x00000020);
              samplesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSamplesFieldBuilder() : null;
            } else {
              samplesBuilder_.addAllMessages(other.samples_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ociweb.protocoltest.PBMessageProvider.PBQuery parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ociweb.protocoltest.PBMessageProvider.PBQuery) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 user = 1;
      private int user_ ;
      /**
       * <code>optional int32 user = 1;</code>
       */
      public boolean hasUser() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 user = 1;</code>
       */
      public int getUser() {
        return user_;
      }
      /**
       * <code>optional int32 user = 1;</code>
       */
      public Builder setUser(int value) {
        bitField0_ |= 0x00000001;
        user_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 user = 1;</code>
       */
      public Builder clearUser() {
        bitField0_ = (bitField0_ & ~0x00000001);
        user_ = 0;
        onChanged();
        return this;
      }

      // optional int32 year = 2;
      private int year_ ;
      /**
       * <code>optional int32 year = 2;</code>
       */
      public boolean hasYear() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 year = 2;</code>
       */
      public int getYear() {
        return year_;
      }
      /**
       * <code>optional int32 year = 2;</code>
       */
      public Builder setYear(int value) {
        bitField0_ |= 0x00000002;
        year_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 year = 2;</code>
       */
      public Builder clearYear() {
        bitField0_ = (bitField0_ & ~0x00000002);
        year_ = 0;
        onChanged();
        return this;
      }

      // optional int32 month = 3;
      private int month_ ;
      /**
       * <code>optional int32 month = 3;</code>
       */
      public boolean hasMonth() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 month = 3;</code>
       */
      public int getMonth() {
        return month_;
      }
      /**
       * <code>optional int32 month = 3;</code>
       */
      public Builder setMonth(int value) {
        bitField0_ |= 0x00000004;
        month_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 month = 3;</code>
       */
      public Builder clearMonth() {
        bitField0_ = (bitField0_ & ~0x00000004);
        month_ = 0;
        onChanged();
        return this;
      }

      // optional int32 date = 4;
      private int date_ ;
      /**
       * <code>optional int32 date = 4;</code>
       */
      public boolean hasDate() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 date = 4;</code>
       */
      public int getDate() {
        return date_;
      }
      /**
       * <code>optional int32 date = 4;</code>
       */
      public Builder setDate(int value) {
        bitField0_ |= 0x00000008;
        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 date = 4;</code>
       */
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00000008);
        date_ = 0;
        onChanged();
        return this;
      }

      // optional int32 sampleCount = 5;
      private int sampleCount_ ;
      /**
       * <code>optional int32 sampleCount = 5;</code>
       */
      public boolean hasSampleCount() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 sampleCount = 5;</code>
       */
      public int getSampleCount() {
        return sampleCount_;
      }
      /**
       * <code>optional int32 sampleCount = 5;</code>
       */
      public Builder setSampleCount(int value) {
        bitField0_ |= 0x00000010;
        sampleCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 sampleCount = 5;</code>
       */
      public Builder clearSampleCount() {
        bitField0_ = (bitField0_ & ~0x00000010);
        sampleCount_ = 0;
        onChanged();
        return this;
      }

      // repeated .pbexample.PBQuery.PBSample samples = 6;
      private java.util.List<com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample> samples_ =
        java.util.Collections.emptyList();
      private void ensureSamplesIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          samples_ = new java.util.ArrayList<com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample>(samples_);
          bitField0_ |= 0x00000020;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample, com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample.Builder, com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSampleOrBuilder> samplesBuilder_;

      /**
       * <code>repeated .pbexample.PBQuery.PBSample samples = 6;</code>
       */
      public java.util.List<com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample> getSamplesList() {
        if (samplesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(samples_);
        } else {
          return samplesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .pbexample.PBQuery.PBSample samples = 6;</code>
       */
      public int getSamplesCount() {
        if (samplesBuilder_ == null) {
          return samples_.size();
        } else {
          return samplesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .pbexample.PBQuery.PBSample samples = 6;</code>
       */
      public com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample getSamples(int index) {
        if (samplesBuilder_ == null) {
          return samples_.get(index);
        } else {
          return samplesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .pbexample.PBQuery.PBSample samples = 6;</code>
       */
      public Builder setSamples(
          int index, com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample value) {
        if (samplesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSamplesIsMutable();
          samples_.set(index, value);
          onChanged();
        } else {
          samplesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .pbexample.PBQuery.PBSample samples = 6;</code>
       */
      public Builder setSamples(
          int index, com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample.Builder builderForValue) {
        if (samplesBuilder_ == null) {
          ensureSamplesIsMutable();
          samples_.set(index, builderForValue.build());
          onChanged();
        } else {
          samplesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pbexample.PBQuery.PBSample samples = 6;</code>
       */
      public Builder addSamples(com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample value) {
        if (samplesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSamplesIsMutable();
          samples_.add(value);
          onChanged();
        } else {
          samplesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .pbexample.PBQuery.PBSample samples = 6;</code>
       */
      public Builder addSamples(
          int index, com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample value) {
        if (samplesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSamplesIsMutable();
          samples_.add(index, value);
          onChanged();
        } else {
          samplesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .pbexample.PBQuery.PBSample samples = 6;</code>
       */
      public Builder addSamples(
          com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample.Builder builderForValue) {
        if (samplesBuilder_ == null) {
          ensureSamplesIsMutable();
          samples_.add(builderForValue.build());
          onChanged();
        } else {
          samplesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pbexample.PBQuery.PBSample samples = 6;</code>
       */
      public Builder addSamples(
          int index, com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample.Builder builderForValue) {
        if (samplesBuilder_ == null) {
          ensureSamplesIsMutable();
          samples_.add(index, builderForValue.build());
          onChanged();
        } else {
          samplesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pbexample.PBQuery.PBSample samples = 6;</code>
       */
      public Builder addAllSamples(
          java.lang.Iterable<? extends com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample> values) {
        if (samplesBuilder_ == null) {
          ensureSamplesIsMutable();
          super.addAll(values, samples_);
          onChanged();
        } else {
          samplesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .pbexample.PBQuery.PBSample samples = 6;</code>
       */
      public Builder clearSamples() {
        if (samplesBuilder_ == null) {
          samples_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
          onChanged();
        } else {
          samplesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .pbexample.PBQuery.PBSample samples = 6;</code>
       */
      public Builder removeSamples(int index) {
        if (samplesBuilder_ == null) {
          ensureSamplesIsMutable();
          samples_.remove(index);
          onChanged();
        } else {
          samplesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .pbexample.PBQuery.PBSample samples = 6;</code>
       */
      public com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample.Builder getSamplesBuilder(
          int index) {
        return getSamplesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .pbexample.PBQuery.PBSample samples = 6;</code>
       */
      public com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSampleOrBuilder getSamplesOrBuilder(
          int index) {
        if (samplesBuilder_ == null) {
          return samples_.get(index);  } else {
          return samplesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .pbexample.PBQuery.PBSample samples = 6;</code>
       */
      public java.util.List<? extends com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSampleOrBuilder> 
           getSamplesOrBuilderList() {
        if (samplesBuilder_ != null) {
          return samplesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(samples_);
        }
      }
      /**
       * <code>repeated .pbexample.PBQuery.PBSample samples = 6;</code>
       */
      public com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample.Builder addSamplesBuilder() {
        return getSamplesFieldBuilder().addBuilder(
            com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample.getDefaultInstance());
      }
      /**
       * <code>repeated .pbexample.PBQuery.PBSample samples = 6;</code>
       */
      public com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample.Builder addSamplesBuilder(
          int index) {
        return getSamplesFieldBuilder().addBuilder(
            index, com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample.getDefaultInstance());
      }
      /**
       * <code>repeated .pbexample.PBQuery.PBSample samples = 6;</code>
       */
      public java.util.List<com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample.Builder> 
           getSamplesBuilderList() {
        return getSamplesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample, com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample.Builder, com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSampleOrBuilder> 
          getSamplesFieldBuilder() {
        if (samplesBuilder_ == null) {
          samplesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample, com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSample.Builder, com.ociweb.protocoltest.PBMessageProvider.PBQuery.PBSampleOrBuilder>(
                  samples_,
                  ((bitField0_ & 0x00000020) == 0x00000020),
                  getParentForChildren(),
                  isClean());
          samples_ = null;
        }
        return samplesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:pbexample.PBQuery)
    }

    static {
      defaultInstance = new PBQuery(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:pbexample.PBQuery)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_pbexample_PBQuery_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pbexample_PBQuery_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_pbexample_PBQuery_PBSample_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pbexample_PBQuery_PBSample_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"src/main/protobuf/pb_message.proto\022\tpb" +
      "example\"\320\001\n\007PBQuery\022\014\n\004user\030\001 \001(\005\022\014\n\004yea" +
      "r\030\002 \001(\005\022\r\n\005month\030\003 \001(\005\022\014\n\004date\030\004 \001(\005\022\023\n\013" +
      "sampleCount\030\005 \001(\005\022,\n\007samples\030\006 \003(\0132\033.pbe" +
      "xample.PBQuery.PBSample\032I\n\010PBSample\022\n\n\002i" +
      "d\030\001 \001(\005\022\014\n\004time\030\002 \001(\003\022\023\n\013measurement\030\003 \001" +
      "(\005\022\016\n\006action\030\004 \001(\005B.\n\027com.ociweb.protoco" +
      "ltestB\021PBMessageProviderH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_pbexample_PBQuery_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_pbexample_PBQuery_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_pbexample_PBQuery_descriptor,
              new java.lang.String[] { "User", "Year", "Month", "Date", "SampleCount", "Samples", });
          internal_static_pbexample_PBQuery_PBSample_descriptor =
            internal_static_pbexample_PBQuery_descriptor.getNestedTypes().get(0);
          internal_static_pbexample_PBQuery_PBSample_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_pbexample_PBQuery_PBSample_descriptor,
              new java.lang.String[] { "Id", "Time", "Measurement", "Action", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
